
<h1>薪资查询</h1>

<?php 

echo CHtml::encode($model->getAttributeLabel('total_salary'));
echo CHtml::encode($model->total_salary);

$this->widget('zii.widgets.CDetailView', array(
	'data'=>$model,
	'attributes'=>array(
		'employer_id',
		'salary_date',
		'print_status',
		'total_salary',
		'total_pay',
		'basic_salary',
		'basic_hours',
		'hour_salary',
		'salary_x1',
		'salary_x1_hour',
		'salary_x2',
		'salary_x2_hour',
		'salary_x3',
		'salary_x3_hour',
		'award_quanqin',
		'award_jineng',
		'award_shengchang',
		'award_yeban',
		'award_tegang',
		'award_zhufang',
		'award_nianzi',
		'award_guojie',
		'award_gaowen',
		'award_qita',
		'award_nianzhong',
		'tiaozhengqian',
		'tiaozhenghou',
		'total_debit',
		'debit_nianjia',
		'hours_nianjia',
		'debit_gongsifangjia',
		'hours_gongsifangjia',
		'debit_hunjia',
		'hours_hunjia',
		'debit_chanjia',
		'hours_chanjia',
		'debit_sangjia',
		'hours_sangjia',
		'debit_shijia',
		'hours_shijia',
		'debit_bingjia',
		'hours_bingjia',
		'debit_kuanggong',
		'hours_kuanggong',
		'debit_chidaozaotui',
		'hours_chidaozaotui',
		'debit_qita',
		'personal_tax',
		'personal_insurance',
		'personal_fund',
		'company_tatal_cost',
		'company_insurance',
		'company_fund',
	),
)); ?>